@ECHO off

REM --- script all DDL objects ---
REM script generated by the toll mssql-scripter
REM further info https://github.com/microsoft/mssql-scripter
REM database connection from the environment variable MSSQL_SCRIPTER_CONNECTION_STRING
REM further info https://github.com/microsoft/mssql-scripter/blob/dev/doc/usage_guide.md#environment-variables

REM execute tool
call mssql-scripter %1 %2 %3 %4 %5 %6 %7 %8 %9
